logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) - %clr([%t]){faint} %X{log_id} %clr(%logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    level: info
  file:
     name: /www/server/tomcat/webapps/log/sign/bug.log
  logback:
    rollingpolicy:
      max-file-size: 2MB
  level:
    root: info
